name: Deploy to Tsuru

on:
  push:
    branches:
      - ServletV5-(Ready-to-deploy)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Install Tsuru CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/tsuru/tsuru-client/master/install.sh | sh
          echo "Tsuru CLI installed"

      - name: Add Target
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
          TSURU_HOST: ${{ secrets.TSURU_HOST }}
        run: |
          tsuru target-add default $TSURU_HOST -s

      - name: Set Environment Variables
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
        run: |
          tsuru env-set AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }} AWS_S3_SECRET_KEY=${{ secrets.AWS_S3_SECRET_KEY }} --app bioeng-hhack-app

      - name: Rename war file
        run: |
          mv ./build/libs/HHDatabase-1.0-SNAPSHOT.war ./ROOT.war

      - name: Deploy to Tsuru
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
        run: |
          tsuru app-deploy -a bioeng-hhack-app ROOT.war
